
services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - '8088:8080'
    volumes:
      - /stirlingpdf/extraConfigs:/configs
      - /stirlingpdf/customFiles:/customFiles/
      - /stirlingpdf/logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_GB
    restart: always
